// examples/framework-gallery/nodes/solid-node/client/index.tsx
import type { FrameworkGallerySolidNodeClientNodeProperties } from '../types'
import type { EditorRED } from 'node-red'
import { render } from 'solid-js/web'
import 'virtual:uno.css'
import App from './App'
import { store } from './hydrate'
import { NODE_NAME, NODE_PALETTE_LABEL, NODE_SCOPE } from '../constant'

declare const RED: EditorRED

let dispose: (() => void) | undefined
function destroyApp() {
  dispose?.()
  dispose = undefined
}

RED.nodes.registerType<FrameworkGallerySolidNodeClientNodeProperties>(NODE_NAME, {
  category: 'function',
  color: '#a6bbcf',
  icon: 'solid-node-solid.svg',
  defaults: { name: { value: '' } },
  inputs: 1,
  outputs: 1,
  paletteLabel: NODE_PALETTE_LABEL,
  label() {
    return this.name || NODE_NAME
  },
  oneditprepare() {
    store.hydrate(this)
    destroyApp()
    const target = document.querySelector(`[data-flowup-scope="${NODE_SCOPE}"].flowup-solid-root`)
    if (target) dispose = render(() => App(), target)
  },
  oneditsave() {
    store.commit(this)
    destroyApp()
  },
  oneditcancel() {
    destroyApp()
  },
})

// examples/framework-gallery/plugins/gallery-plugin/client/index.tsx
import type { EditorRED } from 'node-red'
import { render } from 'preact'
import 'virtual:uno.css'
import App from './App'
import { PLUGIN_DISPLAY_NAME, PLUGIN_NAME, PLUGIN_SCOPE } from '../constant'

declare const RED: EditorRED

RED.plugins.registerPlugin(PLUGIN_NAME, {
  onadd() {
    if (RED.sidebar.containsTab(PLUGIN_NAME)) return
    const target = document.createElement('div')
    target.dataset.flowupScope = PLUGIN_SCOPE
    target.className = 'flowup-preact-root'
    RED.sidebar.addTab({
      id: PLUGIN_NAME,
      name: PLUGIN_DISPLAY_NAME,
      label: PLUGIN_DISPLAY_NAME,
      iconClass: 'fa fa-puzzle-piece',
      content: target,
    })
    render(<App />, target)
  },
})
